openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Beneficiary Onboarding API"
  description: "This is the API that is called by the Information Mediator BB when the Registration BB in turn calls its API for registering beneficiaries into the ID Mapper of the Payments BB."
servers:
  - url: "https://payments-hub.example.com"
  - url: "https://account-mapper.example.com"
paths:
  /register-beneficiaries:
    post:
      summary: "Register beneficiaries"
      description: "Register beneficiaries into the ID Mapper of the Payments BB"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterBeneficiaryRequest"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterBeneficiaryResponse"
              examples:
                success:
                  value:
                    ResponseCode: "00"
                    ResponseDescription: "Request successfully received by Pay-BB"
                    RequestID: "915251236706"
                failure:
                  value:
                    ResponseCode: "01"
                    ResponseDescription: "Request not acknowledged by Pay-BB"
                    RequestID: "915251236706"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Register
