openapi: 3.0.0
info:
  title: Bulk Payment API
  version: 1.0.0
paths:
  /bulk-payment:
    post:
      summary: Bulk payment processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RequestID:
                  type: string
                  minLength: 12
                  maxLength: 12
                SourceBBID:
                  type: string
                  minLength: 12
                  maxLength: 12
                BatchID:
                  type: string
                  minLength: 12
                  maxLength: 12
                CreditInstructions:
                  type: array
                  items:
                    type: object
                    properties:
                      InstructionID:
                        type: string
                        minLength: 16
                        maxLength: 16
                      PayeeFunctionalID:
                        type: string
                        minLength: 20
                        maxLength: 20
                      Amount:
                        type: number
                        format: float
                      Currency:
                        type: string
                        minLength: 3
                        maxLength: 3
                      Narration:
                        type: string
                        minLength: 1
                        maxLength: 50
                        nullable: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseCode:
                    type: string
                    minLength: 2
                    maxLength: 2
                  ResponseDescription:
                    type: string
                    maxLength: 200
                  RequestID:
                    type: string
                    minLength: 12
                    maxLength: 12
        '400':
          description: Bad request
