openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Payments BB API"
  description: "This API is to be exposed by the Payments BB; it will be called by the Source BB to gather details on which of the Functional IDs they would have previously stored in the account mapper are in a position to receive a credit transfer."
servers:
  - url: "https://payments-bb.example.com"
paths:
  /credit-instructions:
    post:
      summary: "Submit credit instructions"
      description: "Submit credit instructions to the Payments BB from the Source BB"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreditInstructionRequest"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreditInstructionResponse"
              examples:
                success:
                  value:
                    ResponseCode: "00"
                    ResponseDescription: "Request successfully received by Pay-BB"
                    RequestID: "849324499155"
                failure:
                  value:
                    ResponseCode: "01"
                    ResponseDescription: "Request not acknowledged by Pay-BB"
                    RequestID: "849324499155"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreditInstructionResponse"

components:
  schemas:
    CreditInstructionRequest:
      type: "object"
      properties:
        RequestID:
          type: "string"
          minLength: 12
          maxLength: 12
        SourceBBID:
          type: "string"
          minLength: 12
          maxLength: 12
        BatchID:
          type: "string"
          minLength: 12
          maxLength: 12
        CreditInstructions:
          type: "array"
          items:
            $ref: "#/components/schemas/CreditInstruction"
    CreditInstruction:
      type: "object"
      properties:
        InstructionID:
          type: "string"
          minLength: 16
          maxLength: 16
        PayeeFunctionalID:
          type: "string"
          minLength: 20
          maxLength: 20
        Amount:
          type: "number"
          format: "float"
        Currency:
          type: "string"
          minLength: 3
          maxLength: 3
        Narration:
          type: "string"
          minLength: 1
          maxLength: 50
    CreditInstructionResponse:
      type: "object"
      properties:
        ResponseCode:
          type: "string"
          minLength: 2
          maxLength: 2
          enum: ["00", "01"]
        ResponseDescription:
          type: "string"
          maxLength: 200
        RequestID:
          type: "string"
          minLength: 12
          maxLength: 12